### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by gaspers1** [TiesdeKok/NotebookOpener#1]
I suggest an addition to readme.md:

*\* If you have more Python environments, without **activate.bat**, you can create it from https://github.com/conda/conda-env/blob/develop/bin/activate.bat and just paste it in Scripts folder of the environment you want to use in notebook_opener

**Comment by TiesdeKok** [comment]
Thanks, I did not think about that possibility! I will most definitely look into adding it to the README.

**Comment by gaspers1** [comment]
Well, if you install anaconda at first and additionally add environments, then it might happen, that you don't have **activate.bat** in Scripts folder of each environment, so you can solve this by simply adding it.

**Comment by TiesdeKok** [comment]
Ah, I see your point. Definitely good to know.

**Comment by TiesdeKok** [comment]
I finally got around to update the README file, thanks again for you suggestion!
